* Planificaciones de Ciencias Sociales
** Secuencia Ciudadanía 
*** clase Nº 1
 
*Propósitos:* 

- Propiciar espacios en los que los alumnos puedan tomar la palabra y expresarse.
- Conocer y valorar las formas de participación política y ciudadana.  Analizar el funcionamiento del sistema electoral considerando su importancia como herramienta del sistema democrático y la influencia que ejerce en el proceso de elección de gobernantes.


*Duración de la clase*: 1 hora reloj

*Contenidos*:
- La participación política y ciudadana
  - Qué es un sistema electoral. El voto. Características. Ley Sáenz Peña.
  - La ampliación de derechos cívicos: el voto femenino y la incorporación a las urnas de los/as jóvenes desde los 16 años.

*Organización de la clase*

*Momento 1*: 

Comenzaremos indagando los saberes previos de los/as estudiantes sobre el tema con preguntas disparadoras ¿Saben que este año se celebran elecciones? ¿Qué cargos se elegirán? ¿Cuándo se realizarán? ¿Quiénes pueden votar? 
Se registrarán las respuestas en el pizarrón.

*Momento 2*:
A continuación se conversará con los/as estudiantes acerca de la forma de gobierno de nuestro país: Representativa, republicana y federal haciendo hincapié en la primera característica.

La *forma representativa* significa que si bien el gobierno es ejercido por el pueblo, éste no lo hace en forma directa sino a través de sus representantes, quienes son elegidos a través del voto. Son ellos quienes representan al pueblo en forma plural.
Para reafirmar esto, el artículo 22 de la Constitución de la Nación Argentina declara que 

#+begin_quote
“el pueblo no delibera ni gobierna, sino por medio de sus representantes y autoridades creadas por esta Constitución”.
#+end_quote

Se les preguntará *¿Saben cuáles son las características del voto?*
Se irán registrando en el pizarrón los saberes de los/as estudiantes y aportando los que no estén disponibles.

*El derecho al voto: universal, igual, secreto, libre y obligatorio*
El voto en Argentina tiene las siguientes características: es universal, igual, secreto, libre y obligatorio.
- Universal. Esto significa que todos los argentinos nativos y por opción, independientemente de su sexo, raza, religión, etc., son titulares del derecho al sufragio para las categorías federales a partir de los 16 años cumplidos a la fecha de la elección nacional. En algunas provincias los extranjeros con residencia permanente gozan de derechos políticos a nivel local.
- Igual. Significa que el voto de todas las personas tiene el mismo valor. Este principio se expresa de la siguiente manera: “un elector, un voto”.
- Secreto. El voto es emitido en ciertas condiciones que impiden conocer en qué sentido ha votado cada elector y nadie puede ser compelido antes o después del acto electoral a revelar su voto.
- Libre. El elector no puede ser forzado de ninguna manera a votar a favor o en contra de una agrupación o candidato.
- Obligatorio. Todo elector habilitado está obligado a votar. Cabe destacar, que el ejercicio del sufragio es también un deber cívico para los electores de 16 y 17 años, y para los mayores de 70 años, aunque quienes tengan esas edades, se encuentran exceptuados de ser sancionados por la autoridad competente, en caso de no emitir su voto.

*Momento 3*:

Se les preguntará *¿Siempre fueron así estas características?* Se intentará problematizar e historizar la participación ciudadana y el acceso a los derechos políticos en nuestro país. Para ello se les entregará una fotocopia (anexo 1) que deberán leer y discutir para contestar la pregunta. 
Pueden realizar una línea de tiempo para ordenar los hechos históricos que se mencionan.

**** Ley Sáenz Peña: Voto universal, secreto y obligatorio


En 1912 se promulgó lo que se conoce como la Ley Sáenz Peña o Ley 8.871 a la ley General de Elecciones sancionada por el Congreso de la Nación Argentina, que estableció el voto secreto y obligatorio a través de la confección de un padrón electoral, pero seguía siendo exclusivo para nativos argentinos y naturalizados masculinos y mayores de 18 años. Debe su nombre al hecho de haber sido sancionada durante la presidencia de Roque Sáenz Peña

El 10 de febrero de 1912 el Congreso Nacional sancionó la ley 8.871, que empezaría a conocerse como la "Ley Sáenz Peña", que estableció el voto secreto, obligatorio y universal.

Si bien la ley no era tan universal, porque seguía siendo exclusiva para nativos argentinos y naturalizados masculinos y mayores a 18 años, vino a poner fin al fraude y al soborno que perpetuaba en el poder al régimen oligárquico que comenzó en 1880.

Por su parte, las mujeres debieron esperar 39 años hasta la sanción de la Ley 14.032, de junio de 1951 de la mano de Eva Perón, que con el sufragio femenino comenzó a equilibrar la balanza.

Antes de la ley Saénz Peña, los días de elecciones, los gobernantes de turno hacían valer las libretas de los muertos, compraban votos, quemaban urnas y falsificaban padrones.
"Puede decirse que todos los gobernantes de lo que la historia oficial llama `presidencias históricas`, es decir, las de (Bartolomé) Mitre, (Domingo) Sarmiento y (Nicolás) Avellaneda; y las subsiguientes hasta 1916, son ilegítimas de origen, porque todos los presidentes de aquel período llegaron al gobierno gracias al más crudo fraude electoral", evalúa el historiador Felipe Pigna, en `Los mitos de la historia argentina III`.

La primera aplicación de la ley Sáenz Peña fue en abril de 1912 en Santa Fe y Buenos Aires, y luego permitió que accediera al poder en 1916 el candidato por la Unión Cívica Radical, Hipólito Yrigoyen.

La primera ley electoral había sido sancionada en 1821 en la provincia de Buenos Aires durante el gobierno de Martín Rodríguez, por el impulso de su ministro de gobierno, Bernardino Rivadavia, y establecía el "sufragio universal masculino y voluntario para todos los hombres libres de la provincia" y limitaba exclusivamente la posibilidad de ser electo para cualquier cargo a quienes fueran propietarios.
Sin embargo, esta ley tuvo un alcance limitado, porque la mayoría de la población ni siquiera se enteraba de que se desarrollaban comicios.

La Constitución Nacional de 1853 dejó un importante vacío jurídico sobre el sistema electoral, que fue parcialmente cubierto por la ley 140 de 1857: el voto era masculino y cantado, lo que podía provocarle "inconvenientes" al votante si no sufragaba por lo que imponía el caudillo de su zona.

Por aquella época el país se dividía en 15 distritos electorales, en los que cada votante lo hacía por una lista completa, es decir que contenía los candidatos para todos los cargos.

**** DOCUMENTO ELECCIONES  2015 “HACIENDO UN POCO DE HISTORIA” SUPERVISIÓNDECENTROS EDUCATIVOS

*Cuarta ampliación de la base democrática: voto a los 16 años*

Con treinta años ininterrumpidos de democracia, asistimos hoy a la cuarta etapa de ampliación de la base democrática mediante las modificaciones a la Ley Electoral Nacional que habilitan el voto a partir de los 16 años. La Ley N° 26.774 de Ciudadanía Argentina (sancionada el 31 de octubre de 2012 y promulgada el 1 de noviembre de 2012) tiene por objetivo la ampliación de los derechos políticos de los jóvenes entre 16 y 18 años de edad, constituyendo un nuevo paso en el proceso de construcción de mayor ciudadanía para esta franja de la juventud. La Ley se fundamenta en la Doctrina de Protección Integral de los Derechos de los Niños y el nuevo paradigma desde el que se percibe a la niñez, la adolescencia y la juventud; en la consolidación de un Estado inclusivo y de protección y promoción de los derechos de los niños, niñas y adolescentes que asegura procesos de socialización; en el crecimiento sostenido de la participación y el compromiso político de los jóvenes; en las condiciones evolutivas, intelectuales y de madurez (de los ciudadanos y ciudadanas de 16 años) para formar parte de las decisiones colectivas que les atañen, les afectan y los incluyen. 

Cuadernillo para docentes “Voto a los 16. Democracia, ciudadanía y participación.”
Ministerio de Educación de la Nación

